# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: string
version: version
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: profilename

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
macro-paths: [directorypath]
model-paths: [directorypath]
seed-paths: [directorypath]
snapshot-paths: [directorypath]
test-paths: [directorypath]
packages-install-path: directorypath

target-path: directorypath                # directory which will store compiled SQL files
clean-targets: [directorypath]        # directories to be removed by `dbt clean`

vars:
  <variables>

models:
  <model-configs>

seeds:
  <seed-configs>

snapshots:
  <snapshot-configs>

sources:
  <source-configs>
  
tests:
  <test-configs>
