ae_bootcamp_standupfree:
  target: dev # this is the default target
  outputs:
    ci:
      type: bigquery
      method: service-account
      project: ae-bootcamp-standupfree
      dataset: jaffle_shop
      thread: 4
      keyfile: ae-bootcamp-standupfree-b6b98e0d9a22.json
    dev:
      type: bigquery
      method: service-account
      project: ae-bootcamp-standupfree
      dataset: jaffle_shop
      thread: 4
      keyfile: ae-bootcamp-standupfree-b6b98e0d9a22.json
