ae_bootcamp_standupfree:

  target: "{{ env_var('DBT_TARGET') }}" # this is the default target

  outputs:
    ci:
      type: bigquery
      method: service-account
      project: ae-bootcamp-standupfree
      dataset: dev_jaffle_shop
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEY') }}"

    dev:
      type: bigquery
      method: service-account
      project: ae-bootcamp-standupfree
      dataset: dev_jaffle_shop
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEY') }}"

    preprod:
      type: bigquery
      method: service-account
      project: ae-bootcamp-standupfree
      dataset: preprod_jaffle_shop
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEY') }}"

    prod:
      type: bigquery
      method: service-account
      project: ae-bootcamp-standupfree
      dataset: prod_jaffle_shop
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEY') }}"
