ae_bootcamp_standupfree:

  target: "{{ env_var('DBT_TARGET') }}" # this is the default target

  outputs:
    ci:
      type: bigquery
      method: oauth
      project: ae-bootcamp-standupfree
      dataset: dev_jaffle_shop
      threads: 4
 
    dev:
      type: bigquery
      method: oauth
      project: ae-bootcamp-standupfree
      dataset: dev_jaffle_shop
      threads: 4

    preprod:
      type: bigquery
      method: oauth
      project: ae-bootcamp-standupfree
      dataset: preprod_jaffle_shop
      threads: 4

    prod:
      type: bigquery
      method: oauth
      project: ae-bootcamp-standupfree
      dataset: prod_jaffle_shop
      threads: 4
